.PHONY: run

run:
	./run.sh

reset:
	./reset.sh

update:
	docker pull nutsfoundation/nuts-node:master
	docker pull nutsfoundation/nuts-registry-admin-demo:master
	docker pull nutsfoundation/nuts-demo-ehr:main